device: "cuda"       
epochs: 200
checkpoint_path: "output/best_model.pth"
lr: 0.001
batch_size: 8

# Model related configuration
obj_dim: 4         # Object feature dimension, such as 'lat_dist', 'long_dist', 'abs_vel_x', 'abs_vel_z'
lane_dim: 13       # Dimension of each row of lane data: one-hot (N) + 3 polynomial coefficients; here the example takes 13, which can be adjusted according to the actual situation
imu_dim: 1         # Here simply use 'vf' as the imu feature (other dimensions can be extended)
embed_dim: 32
num_heads: 4
ff_dim: 64
num_layers: 2
hidden_dim: 64
