device: "cuda"           # 或 "cpu"
checkpoint_path: "output/best_model.pth"

# Model related configuration
obj_dim: 4               # Object feature dimension (e.g., lat_dist, long_dist, abs_vel_x, abs_vel_z)
lane_dim: 13             # Lane data dimension per row (one-hot encoding length + number of polynomial coefficients)
imu_dim: 1               # IMU data dimension, here using 'vf'
embed_dim: 32            # Embedding dimension for Transformer/MLP
num_heads: 4             # Number of heads for Transformer multi-head attention
ff_dim: 64               # Hidden layer dimension for Transformer feed-forward network
num_layers: 2            # Number of layers for Transformer encoder
hidden_dim: 64           # Hidden layer dimension for RNN decoder
